### ISSUE TITLE
Create Unit Testing

### ISSUE THREAD

**Issue by mightycorn** [ASMRCleaning/ac-api#77]
Create unit test for the following routes:

- POST /register
- POST /login
- GET /customer
- GET /customer/residence
- POST /customer/residence
- PUT /customer/residence
- DELETE /customer/residence

**Comment by RZ3M** [comment]
https://github.com/ASMRCleaning/ac-api/commit/4d5efa00d9a9545f4bdab6e71c80219a4b0f0390
